name: Deploy

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Deploy to Surge
      run: |
        npm i surge
        node_modules/.bin/surge --domain splitti.me
