name: Deploy

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Deploy to Surge
      run: |
        export SURGE_LOGIN=mr.avgp@gmail.com
        export SURGE_TOKEN=14702e250c70d050c8d27d0239e1f61a
        npm i surge
        node_modules/.bin/surge . splitti.me
